# Use the official SQL Server 2022 image
FROM mcr.microsoft.com/mssql/server:2022-latest

# Expose the default SQL Server port
EXPOSE 1433

# Run SQL Server and keep it running
CMD /opt/mssql/bin/sqlservr
